vich_uploader:
    db_driver: orm
    mappings:
        profile_images:
            uri_prefix:         '%app.path.profile%'
            upload_destination: '%kernel.project_dir%/public%app.path.profile%'